services:
  postgres:
    image: postgres:15
    container_name: warehouse_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: WarehouseDB
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  warehouse:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "7144:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080

      - Databases__Postgres__ConnectionString=Host=postgres;Port=5432;Database=WarehouseDB;Username=postgres;Password=postgres;Include Error Detail=true

      - UsedDatabase=Postgres
      - AllowedHosts=*

volumes:
  postgres_data:
